config/routes.rb
Rails.application.routes.draw do
  root to: "expressions#index"
  resources :expressions

end

app/models/expression.rb
class Expression < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/expressions_controller.rb
class ExpressionsController < ApplicationController
  before_action :set_expression, only: [:show, :edit, :update, :destroy]

  # GET /expressions
  # GET /expressions.json
  def index
    #@expressions = Expression.all
    @expressions = Expression.order(:expression)
  end

  # GET /expressions/1
  # GET /expressions/1.json
  def show
  end

  # GET /expressions/new
  def new
    @expression = Expression.new
  end

  # GET /expressions/1/edit
  def edit
  end

  # POST /expressions
  # POST /expressions.json
  def create
    @expression = Expression.new(expression_params)

    respond_to do |format|
      if @expression.save
        format.html { redirect_to @expression, notice: 'Expression was successfully created.' }
        format.json { render :show, status: :created, location: @expression }
      else
        format.html { render :new }
        format.json { render json: @expression.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expressions/1
  # PATCH/PUT /expressions/1.json
  def update
    respond_to do |format|
      if @expression.update(expression_params)
        format.html { redirect_to @expression, notice: 'Expression was successfully updated.' }
        format.json { render :show, status: :ok, location: @expression }
      else
        format.html { render :edit }
        format.json { render json: @expression.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expressions/1
  # DELETE /expressions/1.json
  def destroy
    @expression.destroy
    respond_to do |format|
      format.html { redirect_to expressions_url, notice: 'Expression was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expression
      @expression = Expression.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expression_params
      params.require(:expression).permit(:expression, :explanation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expressions_helper.rb
module ExpressionsHelper
end

app/views/expressions/_form.html.erb
<%= form_for(@expression) do |f| %>
  <% if @expression.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@expression.errors.count, "error") %> prohibited this expression from being saved:</h2>

      <ul>
      <% @expression.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  	<p>
      <%= f.label :expression %><br>
      <%= f.text_field :expression, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :explanation %><br>
      <%= f.text_area :explanation, class: 'form-control' %>
    </p>
  </div>
  <div class="actions">
  	<p>
      <%= f.submit class: 'btn btn-primary' %>
    </p>
  </div>
<% end %>

app/views/expressions/edit.html.erb
<h1>Editing Expression</h1>

<%= render 'form' %>

<%= link_to 'Show', @expression, class: 'btn btn-default' %>
<%= link_to 'List', expressions_path, class: 'btn btn-default' %>
<%= link_to 'Destroy', @expression, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

app/views/expressions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Expressions</h1>
<%= link_to 'New Expression', new_expression_path, class: 'btn btn-default' %>
<table class='table'>
  <thead>
    <tr>
      <th>Expression</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expressions.each do |expression| %>
      <tr>
        <td><%= link_to expression.expression, expression %></td>                
      </tr>
    <% end %>
  </tbody>
</table>

app/views/expressions/new.html.erb
<h1>New Expression</h1>

<%= render 'form' %>

<%= link_to 'Back', expressions_path, class: 'btn btn-default' %>

app/views/expressions/show.html.erb
<p>
	<h1><%= @expression.expression %></h1>
</p>
<p>
	<%= @expression.explanation %>
</p>
<p>
	<%= link_to 'Edit', edit_expression_path(@expression), class: 'btn btn-default' %>
	<%= link_to 'List', expressions_path, class: 'btn btn-default' %>
</p>

app/views/layouts/_messages.html.erb
<% flash.each do |name, message| %>
  <% if message.is_a?(String) %>
    <%= content_tag :div, message, class: "flash_#{name}" %>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
	<li><%= link_to 'Home', root_path %></li>
	<%= render 'layouts/navigation_links' %>
</ul>

app/views/layouts/_navigation_links.html.erb
<%# add navigation lniks to this file%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Japanese Made English" %></title>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Japanese Made English" %>">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
  	<%= render 'layouts/navigation' %>
  </header>
  <div class="container">
    <main role="main">
  	  <%= render 'layouts/messages' %>
  	  <%= yield %>
    </main>
  </div>  
</body>
</html>